# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_urls', to='core.Article')),
            ],
        ),
    ]
