# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archiving', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedarticle',
            name='service',
            field=models.CharField(default='archive.org', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='archivedarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_urls', to='core.Article'),
        ),
    ]
