# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiving', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedarticle',
            name='url',
            field=models.URLField(max_length=450),
        ),
    ]
