# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_url', models.URLField()),
                ('archiving_state', models.CharField(blank=True, choices=[('ARCHIVED', 'Archived'), ('ARCHIVING', 'Archiving in progress'), ('NO_ARCHIVING', 'No archiving is needed')], max_length=12)),
                ('crawling_state', models.CharField(choices=[('CRAWLED', 'Crawled'), ('CRAWLING', 'Crawling in progress'), ('PROGRAMMED', 'Crawling programmed')], default='PROGRAMMED', max_length=10)),
                ('detected_preservation_tags', models.CharField(blank=True, max_length=37)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_crawled', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RSSFeed',
            fields=[
                ('feed_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Feed')),
                ('rss_url', models.URLField()),
            ],
            bases=('core.feed',),
        ),
        migrations.CreateModel(
            name='TwitterFeed',
            fields=[
                ('feed_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Feed')),
                ('account_name', models.CharField(max_length=15)),
            ],
            bases=('core.feed',),
        ),
        migrations.AddField(
            model_name='article',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Feed'),
        ),
    ]
