# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='archiving_state',
            field=models.CharField(blank=True, choices=[(None, 'Not archived'), ('ARCHIVED', 'Archived'), ('ARCHIVING', 'Archiving'), ('ERROR', 'An error occured')], max_length=12, null=True),
        ),
    ]
