# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 15:55
from __future__ import unicode_literals

import crawler.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171027_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rssfeed',
            name='feed_ptr',
        ),
        migrations.RemoveField(
            model_name='twitterfeed',
            name='feed_ptr',
        ),
        migrations.AddField(
            model_name='feed',
            name='url',
            field=models.URLField(default='https://twitter.com/toutenrab',
                help_text='Enter a RSS feed url or a twitter account URL.',
                validators=[crawler.core.validators.valid_feed_url]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RSSFeed',
        ),
        migrations.DeleteModel(
            name='TwitterFeed',
        ),
    ]
