# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 13:17
from __future__ import unicode_literals

import crawler.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171027_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_url',
        ),
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.URLField(db_index=True, default='', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feed',
            name='url',
            field=models.URLField(help_text='Enter a RSS feed url or a twitter account URL.', unique=True, validators=[crawler.core.models.valid_feed_url]),
        ),
    ]
