# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 15:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171029_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='crawled_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 10, 29, 15, 1, 5, 961120, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
