# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171029_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='name',
            field=models.CharField(default='Change me please', max_length=120),
            preserve_default=False,
        ),
    ]
