# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0006_feed_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreservationTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('leaf_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='detected_preservation_tags',
        ),
        migrations.CreateModel(
            name='NotFoundOnlyTag',
            fields=[
                ('preservationtag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.PreservationTag')),
                ('value', models.BooleanField()),
            ],
            bases=('core.preservationtag',),
        ),
        migrations.CreateModel(
            name='PriorityTag',
            fields=[
                ('preservationtag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.PreservationTag')),
                ('value', models.BooleanField()),
            ],
            bases=('core.preservationtag',),
        ),
        migrations.CreateModel(
            name='ReleaseDateTag',
            fields=[
                ('preservationtag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.PreservationTag')),
                ('value', models.DateTimeField()),
            ],
            bases=('core.preservationtag',),
        ),
        migrations.AddField(
            model_name='preservationtag',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preservation_tags', to='core.Article'),
        ),
        migrations.AddField(
            model_name='preservationtag',
            name='content_type',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
