# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20171031_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasedatetag',
            name='value',
            field=models.DateTimeField(null=True),
        ),
    ]
