# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20171101_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='url',
            field=models.URLField(default='http://fixmerightnow.please'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='use_resource_type_dir',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='use_unique_name',
            field=models.BooleanField(default=True),
        ),
    ]
