# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 22:31
from __future__ import unicode_literals

import crawler.core.models
from django.db import migrations
import slugger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20171101_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=slugger.fields.AutoSlugField(default='oh-dear', populate_from='url', slugify=crawler.core.models.slugify_article_url),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feed',
            name='slug',
            field=slugger.fields.AutoSlugField(default='oh-dear', populate_from='name'),
            preserve_default=False,
        ),
    ]
