# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20171101_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='crawling_state',
        ),
        migrations.AddField(
            model_name='article',
            name='preservation_state',
            field=models.CharField(blank=True, choices=[('PRESERVE', 'Should preserve this article'), ('PRESEREVED', 'Has been stored in order to be archived'), ('NO_PRESERVE', 'Preservation not required')], max_length=11),
        ),
        migrations.AlterField(
            model_name='article',
            name='archiving_state',
            field=models.CharField(blank=True, choices=[('ARCHIVED', 'Archived'), ('ARCHIVING', 'Archiving')], max_length=12),
        ),
    ]
