# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20171103_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='FontResource',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Resource')),
            ],
            bases=('core.resource',),
        ),
    ]
