# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20171103_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='archiving_state',
            field=models.CharField(blank=True, choices=[('ARCHIVED', 'Archived'), ('ARCHIVING', 'Archiving'), ('ERROR', 'An error occured')], max_length=12, null=True),
        ),
    ]
