# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20171105_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='Title not detected', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='preservation_state',
            field=models.CharField(blank=True, choices=[('PRESERVE', 'Should preserve'), ('STORED', 'Has been stored'), ('NO_PRESERVE', 'Not required')], max_length=11),
        ),
    ]
