# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20171112_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='preservation_state',
            field=models.CharField(blank=True, choices=[('PRESERVE', 'Will download resources soon'), ('PRESERVING', 'Downloading resources'), ('STORED', 'Has been stored'), ('NO_PRESERVE', 'Not required')], max_length=11),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='Detecting title', max_length=200),
        ),
    ]
