# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20171124_1456'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FontResource',
        ),
        migrations.DeleteModel(
            name='HTMLResource',
        ),
        migrations.DeleteModel(
            name='ImageResource',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.DeleteModel(
            name='ScriptResource',
        ),
        migrations.DeleteModel(
            name='StyleResource',
        ),
    ]
