# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notfoundonlytag',
            table='scraping_notfoundonlytag',
        ),
        migrations.AlterModelTable(
            name='prioritytag',
            table='scraping_prioritytag',
        ),
        migrations.AlterModelTable(
            name='releasedatetag',
            table='scraping_releasedatetag',
        ),
    ]
